### ISSUE TITLE
Script stops execution of events if iCal has a color unknown to Google Calendar

### ISSUE THREAD

**Issue by obbardc** [derekantrican/GAS-ICS-Sync#308] opened 2023-01-26 14:17 UTC
Hi! I am really loving this script, thanks for supporting it.

It seems that there are two issues I want to create here:

1) (a side note) If an event fails to be added to the calander, it stops executing all other events. If this happens early in the list, then the script effectively ignores all the other events to process. Would it be worth having a try/catch around each event in the for loop?

```
      vevents.forEach(function(e){
        processEvent(e, calendarTz);
      });
```

2) iCal events with an unsupported `color` (e.g. `khaki`) cause the Google API to return an error and this error is just thrown and then the script just exits (see point 1 above). We should sanitise the `colorId` and make sure that the Google API supports that colour. For now, I have simply commented these three lines out since my events don't need colours.

```
  if (event.hasProperty('color')){
    newEvent.colorId = event.getFirstPropertyValue('color').toString();
  }
```

**Comment by obbardc** [comment] 2023-01-26 14:24
An example ical event (see `COLOR:khaki`):
```
BEGIN:VEVENT
UID:ID
DTSTAMP:20221108T125544Z
DTSTART;TZID=Europe/London:20221111T100000
DTEND;TZID=Europe/London:20221111T103000
SEQUENCE:3
SUMMARY:summary
LOCATION:location
TRANSP:OPAQUE
CLASS:PUBLIC
CREATED:20221109T105640Z
LAST-MODIFIED:20221109T105657Z
COLOR:khaki
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;CN=Name;CUTYPE=INDIVIDUAL:mailto:email@example.com
ORGANIZER:mailto:email@example.com
END:VEVENT
```

**Comment by derekantrican** [comment] 2023-01-27 19:18
May be a dupe of #93

**Comment by simonegiusti** [comment] 2023-09-23 15:54
Hello,
I have a problem with COLOR: tag ...

This works:
```
BEGIN:VCALENDAR
PRODID:rockjob calendar2
VERSION:2.0
METHOD:REQUEST
X-WR-CALNAME:rockjob calendar2
X-WR - TimeZone: UTC
BEGIN:VEVENT
UID:260
DTSTAMP:20230923T174352Z
CREATED:20230923T174352Z
LOCATION:Sala Prove - RHO
SEQUENCE:20230923174352
STATUS:CONFIRMED
LAST-MODIFIED:20230923T174352Z
DESCRIPTION:
SUMMARY:PP, RHO - Sala Prove
DTSTART:20231023
DTEND:20231023
X-FUNAMBOL-ALLDAY:TRUE
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
TRANSP:OPAQUE
END:VEVENT

```

This does not:

BEGIN:VCALENDAR
PRODID:rockjob calendar2
VERSION:2.0
METHOD:REQUEST
X-WR-CALNAME:rockjob calendar2
X-WR - TimeZone: UTC
BEGIN:VEVENT
UID:260
DTSTAMP:20230923T174352Z
CREATED:20230923T174352Z
**COLOR:RED**
LOCATION:Sala Prove - RHO
SEQUENCE:20230923174352
STATUS:CONFIRMED
LAST-MODIFIED:20230923T174352Z
DESCRIPTION:
SUMMARY:PP, RHO - Sala Prove
DTSTART:20231023
DTEND:20231023
X-FUNAMBOL-ALLDAY:TRUE
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
TRANSP:OPAQUE
END:VEVENT

this is the error:
![image](https://github.com/derekantrican/GAS-ICS-Sync/assets/21348710/663aac97-1d02-40be-9e88-954fdff520be)

Any suggestion appreciated ..

**Comment by obbardc** [comment] 2023-09-23 16:20
I think we need to ignore the colour tag if it's not able to be mapped to a gcal colour.

**Comment by jonas0b1011001** [comment] 2023-09-23 16:21
@simonegiusti Please test the following change:

Replace [Helpers.gs lines 475-477](https://github.com/derekantrican/GAS-ICS-Sync/blob/e5cd8e02417ee38a04eadbd795201822dbac2e2d/Helpers.gs#L475)
```
  if (event.hasProperty('color')){
    newEvent.colorId = event.getFirstPropertyValue('color').toString();
  }
```

with:
```
  if (event.hasProperty('color')){
    let colorID = event.getFirstPropertyValue('color').toString();
    if (Object.keys(CalendarApp.EventColor).includes(colorID)){
      newEvent.colorId = CalendarApp.EventColor[colorID];
    }else if(Object.values(CalendarApp.EventColor).includes(colorID)){
      newEvent.colorId = colorID;
    }; //else unsupported value
  }
```

**Comment by simonegiusti** [comment] 2023-09-23 17:02
> @simonegiusti Please test the following change:
> 
> Replace [Helpers.gs lines 475-477](https://github.com/derekantrican/GAS-ICS-Sync/blob/e5cd8e02417ee38a04eadbd795201822dbac2e2d/Helpers.gs#L475)
> 
> ```
>   if (event.hasProperty('color')){
>     newEvent.colorId = event.getFirstPropertyValue('color').toString();
>   }
> ```
> 
> with:
> 
> ```
>   if (event.hasProperty('color')){
>     let colorID = event.getFirstPropertyValue('color').toString();
>     if (Object.keys(CalendarApp.EventColor).includes(colorID)){
>       newEvent.colorId = CalendarApp.EventColor[colorID];
>     }else if(Object.values(CalendarApp.EventColor).includes(colorID)){
>       newEvent.colorId = colorID;
>     }; //else unsupported value
>   }
> ```

Now it works perfectly !!
Many thanks ...

**Comment by obbardc** [comment] 2023-09-24 09:13
This should be open until it's merged right ?

**Comment by jonas0b1011001** [comment] 2023-09-24 10:15
@obbardc Does this fix your 2. issue aswell?

**Comment by obbardc** [comment] 2023-09-27 11:02
@jonas0b1011001 yeah, it just doesn't set the colour as expected :-) Can you open a PR, please ?

**Comment by jonas0b1011001** [comment] 2023-09-27 14:00
> @jonas0b1011001 yeah, it just doesn't set the colour as expected :-) Can you open a PR, please ?

Well we are limited to the colors google offers us. We have discussed manually matching colors a while ago but i have no idea how to do that.

**Comment by obbardc** [comment] 2023-09-27 14:10
> > @jonas0b1011001 yeah, it just doesn't set the colour as expected :-) Can you open a PR, please ?
> 
> Well we are limited to the colors google offers us. We have discussed manually matching colors a while ago but i have no idea how to do that.

No, I mean with this patch it is fine. If the ics has a colour which google doesn't understand, it sets it to default. Which is good for me.

I don't care about colours in the destination calendar anyway ;-).

**Closed** 2023-12-13 16:16 UTC
Labels: bug
