### ISSUE TITLE
Recurring event with many exceptions errors out

### ISSUE THREAD

**Issue by wfaulk** [derekantrican/GAS-ICS-Sync#271] opened 2022-05-16 21:03 UTC
I have an event that was set up ages ago and has a large number of exceptions (`EXDATE`s). When GAS-ICS-Sync tries to copy it from one Google Calendar to another, the script halts and shows this error:

```
GoogleJsonResponseException: API call to calendar.events.insert failed with error: A provided value exceeds the allowed size limit.
(anonymous) @ Helpers.gs:228
callWithBackoff @ Helpers.gs:877
processEvent @ Helpers.gs:227
(anonymous) @ Code.gs:202
startSync @ Code.gs:201
```

Those line numbers may be off; I have made some changes to work around the problem for now. I added this as the first `if` inside `catch(err)` at Helpers.gs:880:

      if ( err.message.includes("provided value exceeds the allowed size limit") ) {
        Logger.log("Error, too many exceptions in event recurrence?");
        return null;
      } else if ( err.message.includes("is not a function")…

I don't get that event, but at least it completes for the other events.

Here is an expurgated ICS file that reproduces the issue: https://pastebin.com/raw/icj2LN5n

**Comment by jonas0b1011001** [comment] 2022-05-17 04:08
This seems to be an undocumented limitation of google's API and therefore is a _can't fix_.

However you can avoid the issue by running the script with _onlyFutureEvents = true_ and adding the following code to [Helpers.gs line 512](https://github.com/derekantrican/GAS-ICS-Sync/blob/33c80563124669bf68c4ef4e208df3913236360a/Helpers.gs#L512)

```
var exDates = event.getAllProperties('exdate');
   exDates.forEach(function(e){
  var ex = new ICAL.Time.fromString(e.getFirstValue().toString());
  if (ex < newStartDate){
    event.removeProperty(e);
  }
});
```

**Comment by wfaulk** [comment] 2022-05-17 18:34
Well, at the very least, GAS-ICS-Sync shouldn't *crash* as a result of encountering such an event.

**Comment by derekantrican** [comment] 2023-03-22 20:05
I'm going to close this as a dupe of #282 (in regards to the "shouldn't crash" suggestion)

**Closed by derekantrican** 2023-03-22 20:05 UTC
Labels: bug
