### ISSUE TITLE
On saving the new copy on google app scripts I get an error 

### ISSUE THREAD

**Issue by heyaj19** [derekantrican/GAS-ICS-Sync#100] opened 2020-02-14 22:30 UTC
With zero changes and taking a copy of the fike

This is the error SyntaxError: Unexpected identifier (line 129, file "Code.gs")Dismiss

**Comment by derekantrican** [comment] 2020-02-14 22:37
Duplicate of #98 . Please look there fore the solution

**Closed by derekantrican** 2020-02-14 22:37 UTC
Labels: bug
