### ISSUE TITLE
[Request] Skipping updates if source not reached

### ISSUE THREAD

**Issue by Wisoxx** [derekantrican/GAS-ICS-Sync#377] opened 2023-10-18 20:53 UTC
### Is your feature request related to a problem? Please describe.

I use the script to update my plan from the university site, but the problem is that half of the time the site can't be reached, so there are no items in the schedule list at all, so the script thinks there shouldn't be anything and it deletes everything and then on the next check it reaches the site and starts adding everything again.

### Describe the solution you'd like

What if the script remembers the origin of events and if the source can't be reached, then it ignores those items. However, when the source is no longer on the list, the events should be removed

**Comment by derekantrican** [comment] 2023-10-19 16:17
Seems like a dupe of https://github.com/derekantrican/GAS-ICS-Sync/issues/343

**Closed** 2023-10-25 19:28 UTC
