### ISSUE TITLE
Replace timeBased().after(howFrequent) with timeBased().everyMinutes(howFrequent)

### ISSUE THREAD

**Issue by reclab** [derekantrican/GAS-ICS-Sync#114] opened 2020-03-27 21:36 UTC
Fist of all, thanks for this fantastic script!!

The creation of the `install()` trigger is failing every few hours with a generic "server error" when executing 
```
      ScriptApp.newTrigger("install").timeBased().after(howFrequent * 60 * 1000).create();//Schedule next Execution
```
`howFrequent` is set to 5 minutes. 
I'm using V8 runtime (but failures where happening also with previous version).
I solved the problem by using a `everyMinutes()` trigger, which also simplifies the code.

```
function install(){
  try{
    deleteAllTriggers(); //Delete any already existing triggers so we don't create excessive triggers

    if (howFrequent < 1){
      throw "[ERROR] \"howFrequent\" must be greater than 0.";
    }
    else{
      ScriptApp.newTrigger("startSync").timeBased().everyMinutes(howFrequent).create();
    }
  }catch(e){
    install();//Retry on error
  }
}
```
Now it works without problems (I could also remove `deleteAllTriggers()` ...)

**Comment by derekantrican** [comment] 2020-03-27 21:42
Sounds like a duplicate of #110 . I'm going to close this but feel free to let me know if that's not the case

**Closed by derekantrican** 2020-03-27 21:42 UTC
Labels: bug

**Comment by reclab** [comment] 2020-03-27 21:46
You are right, I missed it
