### ISSUE TITLE
TypeError: Cannot read property 'dateTime' of undefined (line 493, file "Helpers")

### ISSUE THREAD

**Issue by javedrahman** [derekantrican/GAS-ICS-Sync#133] opened 2020-06-06 12:05 UTC
- Description of the problem - I am getting an error after upgrading to the new version.
- Screenshots 
![image](https://user-images.githubusercontent.com/11033953/83943762-66fef600-a7f6-11ea-81d2-bfc97fcb1de7.png)

- An input ics string that can reproduce the problem

You can see [this issue](https://github.com/derekantrican/GAS-ICS-Sync/issues/34) for an example of good information when submitting a bug

**Comment by jonas0b1011001** [comment] 2020-06-06 18:41
Seems like a duplicate of #115 , without additional info i can only suggest the same change as mentioned there.

Did the same ics file work with the previous version?

**Comment by derekantrican** [comment] 2020-06-15 23:50
@javedrahman Any update on this? What version are you running?

**Comment by javedrahman** [comment] 2020-06-20 12:33
Hi. I am on version 5.3. Instead of using the Install method, I have created a timed trigger for startSync to run every 15 minutes. It actually seems to sync just fine but throws the error at the end so overall the script shows as Failed in My Executions.

I think there is an issue with an item in my calendar. because I tried changing the date range for the ICS export and now it does not always fail.

**Comment by jonas0b1011001** [comment] 2020-06-20 12:44
Please try this solution [here](https://github.com/derekantrican/GAS-ICS-Sync/issues/135#issuecomment-644348397), this should fix your issue too. Unfortunately that's a common problem in 5.3.

**Comment by derekantrican** [comment] 2020-08-12 22:22
Seems like this is a duplicate of #135  so I'm going to close it as such

**Closed by derekantrican** 2020-08-12 22:22 UTC
Labels: bug
