### ISSUE TITLE
ParserError: invalid ical body. component began but did not end

### ISSUE THREAD

**Issue by amir-ziaei** [derekantrican/GAS-ICS-Sync#390] opened 2023-12-13 08:31 UTC
### The problem

Starting facing this error since like last week?
<img width="1691" alt="image" src="https://github.com/derekantrican/GAS-ICS-Sync/assets/26747997/a7ad97ab-3447-4db1-a413-6df0c509b3ef">
Been using the script for ~1 year and everything was alright up until now.

Any idea what might have caused this?

### Version of GAS-ICS-Sync

5.6

**Comment by jonas0b1011001** [comment] 2023-12-13 10:47
Even tough the Error message is different, this sounds awfully similar to #388. Can you please check if #386 solves the problem.

**Comment by Kucladell** [comment] 2023-12-13 14:03
This error is what I got when I had the issue in https://github.com/derekantrican/GAS-ICS-Sync/issues/388 and my initial attempt to fix the ICS file was incomplete. To be specific, when I added END:VCALENDAR at the end (so that the parser is given the content of the ICS file) but didn't add END:VEVENT after each event, this error showed up. I agree with @jonas0b1011001 that this may be an identical issue to https://github.com/derekantrican/GAS-ICS-Sync/issues/388 .

**Comment by derekantrican** [comment] 2023-12-13 16:46
Going to close as a dupe of #388 as others have mentioned

**Closed by derekantrican** 2023-12-13 16:46 UTC
