### ISSUE TITLE
Feature: Add Description and Title to Email Notifications 

### ISSUE THREAD

**Issue by p5hema2** [derekantrican/GAS-ICS-Sync#38] opened 2019-03-28 19:52 UTC
Add Description and Title to Email Notifications

**Comment by derekantrican** [comment] 2019-11-01 19:42
It looks like there was a regression here. It was fixed in https://github.com/jonas0b1011001/GAS-ICS-Sync-CalAPIv3/commit/1ddd0dc845cdb38943d43adf235622dce5f7d026 but the latest version only includes Titles in email notifications, not descriptions. We'll work on that

**Closed** 2024-05-15 22:42 UTC
Labels: enhancement
