### ISSUE TITLE
Duplicate Outlook Events

### ISSUE THREAD

**Issue by geo-ryffraff** [derekantrican/GAS-ICS-Sync#107] opened 2020-02-28 20:01 UTC
I've published my outlook calendar (set to only view when busy) and copied the ICS URL into a copy of the google script. But events are getting duplicated in Google Calendar.

<img width="1479" alt="calendar" src="https://user-images.githubusercontent.com/55811342/75582542-ac09d400-5a20-11ea-9520-4417982ad980.png">

Is there a specific format the Outlook ICS URL has to be in? I've implemented the same procedure with a different outlook calendar ICS URL and the events do not get duplicated. Not sure what steps to take to debug.

**Comment by derekantrican** [comment] 2020-02-28 21:20
@geo-ryffraff Since this only shows "free/busy" info - are you willing to share the ics url here?

**Comment by geo-ryffraff** [comment] 2020-03-02 23:32
Sure. Here it is: 

https://outlook.office365.com/owa/calendar/4ad44446737e410691e5867059efdd74@pangeagroup.com/13dbaf0cd8f44ead9a8e8e1a84c8389c8901723053316893918/calendar.ics

**Comment by derekantrican** [comment] 2020-03-03 15:43
@geo-ryffraff I've had this running for a while and have not been able to reproduce. What version are you running? You should be able to find that near the bottom of your Helpers.gs file at a line starting with `var thisVersion =`

**Comment by geo-ryffraff** [comment] 2020-03-03 15:55
Version 5.2

here are the settings I'm using with Code.gs

```
var howFrequent = 1;                   // What interval (minutes) to run this script on to check for new events
var onlyFutureEvents = false;          // If you turn this to "true", past events will not be synced (this will also removed past events from the target calendar if removeEventsFromCalendar is true)
var addEventsToCalendar = true;        // If you turn this to "false", you can check the log (View > Logs) to make sure your events are being read correctly before turning this on
var modifyExistingEvents = true;       // If you turn this to "false", any event in the feed that was modified after being added to the calendar will not update
var removeEventsFromCalendar = true;   // If you turn this to "true", any event created by the script that is not found in the feed will be removed.
var addAlerts = true;                  // Whether to add the ics/ical alerts as notifications on the Google Calendar events, this will override the standard reminders specified by the target calendar.
var addOrganizerToTitle = false;       // Whether to prefix the event name with the event organiser for further clarity
var descriptionAsTitles = false;       // Whether to use the ics/ical descriptions as titles (true) or to use the normal titles as titles (false)
var addCalToTitle = false;             // Whether to add the source calendar to title
var addAttendees = false;              // Whether to add the attendee list. If true, duplicate events will be automatically added to the attendees' calendar.
var defaultAllDayReminder = -1;        // Default reminder for all day events in minutes before the day of the event (-1 = no reminder, the value has to be between 0 and 40320)
                                       // See https://github.com/derekantrican/GAS-ICS-Sync/issues/75 for why this is neccessary.
var addTasks = false;

var emailWhenAdded = false;            // Will email you when an event is added to your calendar
var emailWhenModified = false;         // Will email you when an existing event is updated in your calendar
var email = "";                        // OPTIONAL: If "emailWhenAdded" is set to true, you will need to provide your email
```

And I'm still getting duplicates:

<img width="1414" alt="Screen Shot 2020-03-03 at 7 54 52 AM" src="https://user-images.githubusercontent.com/55811342/75793544-5c7b1f00-5d24-11ea-90b8-25dfb54454e2.png">

**Comment by jonas0b1011001** [comment] 2020-03-03 15:57
Lower the sync frequency and try again please, 1 minute is too fast for over 700 events.

**Comment by geo-ryffraff** [comment] 2020-03-03 21:30
Ah, okay. I lowered the sync frequency and that seemed to do the trick-- but I had to create a new calendar in order to not see the duplicates. Just reducing the sync frequency didn't seem to "de-pollute" the original calendar. Is that intended behavior?

**Comment by jonas0b1011001** [comment] 2020-03-04 06:45
Well it definitely is not intended but at the same time it is quite hard to prevent once things have gone wrong like they did for you.

For removing old events from the target calendar we are checking all events in the target calendar that where created by the script if they still exist in the source calendar (this is done by checking if the event id is still found in the source). As the duplicates are basically the same event they are all still present in the source calendar and therefore do not get deleted.
We can't just simply scan for duplicate event ids in the target calendar as the ical standard defines cases where multiple events have to share the same id (recurrence).

**Comment by derekantrican** [comment] 2020-03-04 14:49
I think we could probably add some function to remove every event from your target calendars that has the `fromGAS` tag? It wouldn't be called by anything else - you'd have to call it manually

**Comment by jonas0b1011001** [comment] 2020-03-05 13:29
@derekantrican What do you think of adding a _UserProperty_ to indicate that an instance of the script is currently running? That way we could prevent multiple instances to run at the same time which basically is the root cause of the issue.

**Comment by geo-ryffraff** [comment] 2020-03-05 13:40
It does seem to be an edge case-- it's not that difficult to just delete and re-create a new target calendar. I was only asking because a colleague of mine is using this script and he's not at all tech savvy, so the less re-configuration, the better.

**Comment by derekantrican** [comment] 2020-03-05 17:59
Yeah, I think that could be helpful

**Comment by derekantrican** [comment] 2020-03-14 16:39
Since this particular issue is solved, I'm going to close it and track the new suggestion of adding a UserProperty here: #111

**Closed by derekantrican** 2020-03-14 16:39 UTC
Labels: bug
