### ISSUE TITLE
ICS/ICAL sync duplicating events

### ISSUE THREAD

**Issue by DamianJLin** [derekantrican/GAS-ICS-Sync#21] opened 2019-01-30 06:02 UTC
![image](https://user-images.githubusercontent.com/31408307/51961392-ac980a00-24b0-11e9-8d00-cdd6e2fce921.png)

As shown in the screenshot, events are being duplicated. Each event is duplicated exactly twice.

I don't think that this is due to a faulty link because when I let google sync the ICS this does not happen.

**Comment by derekantrican** [comment] 2019-01-30 13:51
Damian,

Could you please share with me the script you are using? derekantrican@gmail.com

**Comment by DamianJLin** [comment] 2019-01-31 06:33
Derek,

 

Sorry, but I have deleted the script. I remember that I got it from one of your repositories and only edited the settings, nothing else.

**Comment by derekantrican** [comment] 2019-01-31 06:52
Ok, well since you don't have a script for me to reference and I haven't been seeing this issue, I'm going to close this issue. If someone else sees the same problem in the future they can report it again

**Comment by douglasb2021** [comment] 2020-04-01 20:13
For whatever reason, the script has created duplicates of all my events from only one of the calendars I have inputted. Any suggestions are welcome. Happy to give more specific info if needed.

**Comment by jonas0b1011001** [comment] 2020-04-01 20:16
Hi, please check #107 maybe you are facing the same issue.

**Comment by douglasb2021** [comment] 2020-04-03 00:23
I tried lowering the frequency as suggested (now at 15 moved from 5) and it's beginning to happen again. Suggestions much appreciated.

**Comment by douglasb2021** [comment] 2020-04-05 16:35
So I tried lowering the frequency as suggested (now at 15) and it was working for a few days but no I've got 14 duplicates of all events on only one calendar. Suggestions?

**Comment by derekantrican** [comment] 2020-04-05 23:44
@douglasb2021 If you are willing, please share your ICS url with us so we can look into it

**Comment by douglasb2021** [comment] 2020-04-05 23:46
https://calendar.google.com/calendar/embed?src=6t3n8vacchggkm5c0ua5mtu5v4s4hrkr%40import.calendar.google.com&ctz=America%2FNew_York

-Brian Douglas

**Comment by derekantrican** [comment] 2020-04-05 23:54
@douglasb2021 I just tried syncing a few times and I'm not seeing any duplicated events. Can you check to make sure you have the latest version of the script? At the bottom of `Helpers.gs` look for a line that says `var thisVersion = 5.2;`

**Comment by douglasb2021** [comment] 2020-04-05 23:55
Yes, it does. However, it typically takes a few days for the duplicate events to be created and once they are there's just more and more of them every day.

**Comment by jonas0b1011001** [comment] 2020-04-06 10:22
Once you have duplicates in your target calendar please open the script, run startSync, open view->log and search for an entry like "Fetched XYZ existing events from targetCalendarName", what number does it say there?

**Comment by aznfury** [comment] 2020-04-09 19:02
I ran across this duplication issue as well but was able to resolve it. In my case, I believe the issue came from me Installing it but then also manually running it immediately afterwards by doing the startSync. After doing this the first few times, I thought, well what the hell, I'll just install it and let it do it's own thing and now no more duplicate entries!

**Comment by douglasb2021** [comment] 2020-04-09 21:35
@jonas0b1011001 I tried to do that but the logs won't load even if I leave it open for a long time. I just tried what @aznfury suggested and I'll let you know if it happens again (hasn't yet).

**Comment by ande2413** [comment] 2020-05-15 16:51
Thanks for this! I've turned this into a [web app](https://script.google.com/macros/d/1GHcV03C1RI9I2X5YFlwhxJ5RwAJNrqaTCnuB9IM2MAg3eY2CBwDy5_BA/edit?usp=sharing) to sync with Google Calendar.  I've noticed duplicate events like @jonas0b1011001 but they seem to resolve themselves when the script runs again. @derekantrican  One question I have is if I modify the Google Calendar event created by this script, for example, add guests, will the event be deleted when it re-syncs because it no longer matches the event coming from the webcal feed?  @douglasb2021 looks like your school uses Blackbaud like mine.  If your school uses G Suite as well, this web app might interest you.  Thanks in advance for your advice.

**Comment by jonas0b1011001** [comment] 2020-05-15 17:07
> if I modify the Google Calendar event created by this script, for example, add guests, will the event be deleted

It will not be deleted but overridden with the version from your feed, we are using _extendedProperties_ to match events from your calendar with the ones in the feed, therefore the event will be matched even if you modify it manually.

**Comment by ande2413** [comment] 2020-05-15 17:21
Gotcha, so if I needed that ability, it would be best to trigger startSync(), rather than install() knowing that all future changes would need to be done manually after the initial sync. @derekantrican   Any known issues with execution time? Any sense of approximately how many events could be synced before it times out?  Curious if it could run an entire academic year with one execution.  Thanks.

**Comment by jonas0b1011001** [comment] 2020-05-15 17:31
Execution time is limited to 360 seconds, processing and syncing a single event takes .3 - .5s on average. With some overhead you will most likely be able to sync 650 to 700 events in a single run (Consecutive runs will continue to add remaining events if the previous run timed out)

**Comment by ande2413** [comment] 2020-05-15 18:59
Thanks, that should be enough then.  Gave your project a shout out on
YouTube.

https://youtu.be/vPOJT_G2hqE

Cheers,

Richard

**Comment by derekantrican** [comment] 2020-05-15 19:09
Thanks for the shoutout! We definitely want to make this into a full web-app so people don't have to look at the code (and work on that has been "pending" for a while - see #8) but we've got some time & knowledge constraints.

**Comment by marcingminski** [comment] 2020-05-15 19:21
Hi, just chipping in to add two things:

Firstly - thank you! The project is fantastic, I am using it in parts of the event aggregator for the Data Community: http://datacommunity.dev/ (Microsoft Data Platform folks)

Secondly, I too noticed only one event (out of many) that keeps getting duplicated but it's rare and I cannot work out why. I will do some debugging and come back with more tangible findings.

**Comment by jonas0b1011001** [comment] 2020-05-15 19:43
> Thanks, that should be enough then. Gave your project a shout out on YouTube. https://youtu.be/vPOJT_G2hqE Cheers, Richard

@ande2413 I'm pretty sure we are able to add an option to detect and **not** override manually changed events. If you need this, feel free to open a  separate topic with a feature request.

> Secondly, I too noticed only one event (out of many) that keeps getting duplicated but it's rare and I cannot work out why. I will do some debugging and come back with more tangible findings.

Will the duplicate stay in the calendar once it is created or does the script clean it up eventually?

**Comment by marcingminski** [comment] 2020-05-15 19:51
seems to be staying forever regardless of the `var removeEventsFromCalendar = false/true;` I am looking at adding more logging to see what's happening.

**Comment by ande2413** [comment] 2020-05-15 21:27
Thanks!  I will add that as a feature request.

**Comment by bandtank** [comment] 2021-04-13 17:07
I've been having this issue with the latest version of the script. It seems to only happen with recurring events, but I have no tested enough to know for sure. There also appears to be a dependence on calendar order in the sourceCalendars array. For example, an event from cal[1] will be duplicated on cal[2] and cal[3], but not cal[0]. I have not been able to reproduce the behavior on demand.

**Comment by jonas0b1011001** [comment] 2021-04-13 17:11
@bandtank Have a look at #185, sounds like this is the same issue.

**Comment by bandtank** [comment] 2021-04-13 17:15
@jonas0b1011001 Yes, that seems to be the same issue. I'll try the latest commit to see if it works.

**Comment by Wickstroem** [comment] 2021-09-03 10:16
After running some tests I found that: ICS-files without any events produced duplicate calenders. Also using non english keybord isnt smart. When I use swedish letters - it creates duplicate calenders.

**Comment by jonas0b1011001** [comment] 2021-09-03 11:06
> Also using non english keybord isnt smart. When I use swedish letters - it creates duplicate calenders

I was able to reproduce this behavior. Can you confirm that
1. it is not creating a new duplicate on each execution of the script
2. the duplicate calendars might randomly dis/reappear after reloading calendar.google.com

**Comment by d-aleman** [comment] 2021-09-27 16:20
> l but was able to resolve it. In my case, I believe the issue came from me Installing it but then also manually running it immediately afterwards by doing the startSync. After doing this the first few times, I thought, well what the hell, I'll just install it and let it do it's own thing a

It's Sept 2021 and I am on v5.6 and had this same issue, which was apparently caused by doing both a "startSync" and "install" as described by aznfury. Every all-day event in my Outlook calendar was copied dozens, then hundreds of times into my Google calendar. Only all-day events were affected. Deleting the Outlook calendar from my Google calendar, uninstalling the GAS-ICS-Sync script, and then installing the GAS-ICS-Sync script again fixed the issue for me.

If hitting both "startSync" and "install" cause replication issues, it would be great for the instructions to specifically warn users from hitting both.

**Closed** 2024-05-27 00:23 UTC
Labels: bug
