### ISSUE TITLE
Error: Bad Request at return Calendar.Events.insert(newEvent, targetCalendarId)

### ISSUE THREAD

**Issue by jrey2216** [derekantrican/GAS-ICS-Sync#289] opened 2022-10-11 20:15 UTC
Script functioned months ago for individual URLs, outside of an issue with recurring events duplicating, which I planned to deal with later. At some point recently, the script shows the error below on every run, for every API URL, for 5.6.

GoogleJsonResponseException: API call to calendar.events.insert failed with error: Bad Request
    at [unknown function](Helpers:228:34)
    at callWithBackoff(Helpers:877:16)
    at processEvent(Helpers:227:20)
    at [unknown function](Code:202:9)
    at startSync(Code:201:15)

Example URL: https://api.rschooltoday.com/feed/as/calendar?key=f8cc02c7-a71b-5fed-952c-e67f003b5cff&output_type=ical&period=1year

![Screen Shot 2022-10-11 at 3 10 52 PM](https://user-images.githubusercontent.com/101893979/195188882-f4f079a2-b56b-41bc-b8d2-d28ebd0032f8.png)

**Comment by jonas0b1011001** [comment] 2022-10-14 00:39
This is actually a duplicate of #258 . The *.ics you provided has at least one event that mixes date and datetime.

> DTSTART;VALUE=DATE:20230220
> DTEND:20230221T055500Z

**Comment by derekantrican** [comment] 2023-03-21 22:29
Closing as a duplicate. Please move all future discussion to #258

**Closed by derekantrican** 2023-03-21 22:29 UTC
Labels: duplicate
