### ISSUE TITLE
Script requires me to run "Install" each day; doesn't persist

### ISSUE THREAD

**Issue by ARGACE** [derekantrican/GAS-ICS-Sync#145] opened 2020-08-03 20:55 UTC
- Each day I run the script's "Install" command from the script's menu.  It always runs a sync immediately, and then continues to keep my google cal up to date, but after an indeterminate amount of time, stops syncing.  Each day I can re-run the "Install" command for the script, but the problem continues.  

Previously I had this script running for the same .ics cal link on two separate google accounts (my work and my home), and thought that there may be a conflict, so I uninstalled the script from my work account and uninstalled / reinstalled the script on my personal account.  however, the above-stated issue was present prior to "double-dipping".   
- Screenshots not applicable

Am I doing something wrong?  why does it sync for a period of time then within 24 hrs always stop syncing?  let me know if you need any additional info or log data as I'd be happy to provide it

**Comment by derekantrican** [comment] 2020-08-03 20:57
May be a duplicate of #137

**Closed** 2020-09-24 02:15 UTC
Labels: bug
