### ISSUE TITLE
The deletion of all events

### ISSUE THREAD

**Issue by fred816** [derekantrican/GAS-ICS-Sync#436] opened 2024-04-22 22:46 UTC
### The problem

The code you developed is super useful, I appreciate it.

It seems like there's a bug where If the registered calendar cannot be retrieved, it deletes all events.

I discovered that if responses.length at line 174 is 0, it deletes all existing events. To resolve this, I added the following code at line 176 and it worked.

Thanks

-------------------------------
if (responses.length == 0)
        continue;
-------------------------------

### Version of GAS-ICS-Sync

5.8

**Comment by derekantrican** [comment] 2024-04-23 03:50
I think this might be a duplicate of #343

**Comment by Lonestarjeepin** [comment] 2024-07-01 15:00
Closing as duplicate of #343

**Closed by Lonestarjeepin** 2024-07-01 15:00 UTC
