### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by Hlaxfors** [derekantrican/GAS-ICS-Sync#110] opened 2020-03-12 19:37 UTC
- about once every 1-2 weeks the script crashes for no apparent reason.
- <img width="1162" alt="Skärmavbild 2020-03-13 kl  6 35 46 fm" src="https://user-images.githubusercontent.com/37196332/76560312-001eb900-64f5-11ea-97d1-e67f262031e1.png">

- I can't reproduce it, it just happens randomly

**Comment by derekantrican** [comment] 2020-03-12 19:52
By "crashes" do you mean it stops running? Like you have to go and start it again manually?

**Comment by Hlaxfors** [comment] 2020-03-12 20:13
Yes, Exactly
It seems to occur more often if i decrease howfrequent below 15, but even at 15 it still closes.

**Comment by Hlaxfors** [comment] 2020-03-12 20:15
<img width="886" alt="Skärmavbild 2020-03-13 kl  7 15 26 fm" src="https://user-images.githubusercontent.com/37196332/76562905-72de6300-64fa-11ea-8006-d62d0e83c504.png">

**Comment by jonas0b1011001** [comment] 2020-03-12 20:30
To me it looks like a duplicate of #77 and #79. Are you running the latest version?

**Comment by derekantrican** [comment] 2020-03-27 21:43
@Hlaxfors Did you check whether you are on the latest version?

**Comment by derekantrican** [comment] 2020-04-24 19:05
Haven't heard back after almost a month so closing this issue

**Closed by derekantrican** 2020-04-24 19:05 UTC
Labels: bug
